# Generated by Django 4.1 on 2022-08-23 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=100)),
                ('mobile_no', models.IntegerField()),
                ('address', models.TextField(max_length=400)),
                ('designation', models.CharField(max_length=70)),
                ('joining_date', models.DateField()),
                ('status', models.CharField(max_length=15)),
                ('department', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ems.department')),
                ('role', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ems.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
