# Generated by Django 4.1 on 2022-08-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0006_alter_employee_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emergency_mobile_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
