# Generated by Django 4.1 on 2022-08-27 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0008_attendenceemployee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttendenceEmployee',
            new_name='AttendanceEmployee',
        ),
        migrations.CreateModel(
            name='Attendnce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendance_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems.attendanceemployee')),
            ],
        ),
    ]
