# Generated by Django 4.1 on 2022-08-27 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0010_rename_attendnce_attendance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttendanceEmployee',
            new_name='EmployeeAttendance',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
