# Generated by Django 4.1 on 2022-08-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0011_rename_attendanceemployee_employeeattendance_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeAttendance',
            new_name='Attendance',
        ),
    ]
