# Generated by Django 4.1 on 2022-08-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0015_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='no_of_leaves',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='leave',
            name='reply',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
