# Generated by Django 4.1 on 2022-08-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0016_leave_no_of_leaves_alter_leave_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='no_of_leaves',
            field=models.IntegerField(default=18),
        ),
    ]
