# Generated by Django 4.1 on 2022-09-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0018_remove_leave_no_of_leaves'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='avtar',
            field=models.ImageField(blank=True, null=True, upload_to='employee_profile_images'),
        ),
    ]
