# Generated by Django 4.1 on 2022-09-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0020_alter_employee_avtar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='avtar',
            field=models.ImageField(blank=True, default='profile.jpg', upload_to='employee_profile_images'),
        ),
    ]
