# Generated by Django 4.1 on 2022-09-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0024_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
