# Generated by Django 4.1 on 2022-09-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0025_events_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='employee_documents'),
        ),
    ]
