# Generated by Django 4.1 on 2022-09-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0026_employee_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employeeid',
            field=models.IntegerField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
