# Generated by Django 4.1 on 2022-09-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0027_employee_employeeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeid',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
