# Generated by Django 4.1 on 2022-09-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0028_alter_employee_employeeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
