# Generated by Django 4.1 on 2022-09-12 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0031_alter_departmentquery_query_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentQuery',
        ),
    ]
