# Generated by Django 4.1 on 2022-09-13 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0034_querycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='querycomment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ems.employee'),
        ),
    ]
