# Generated by Django 4.1 on 2022-09-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0042_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events'),
        ),
    ]
