# Generated by Django 4.1 on 2022-09-27 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0044_newuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='document',
        ),
    ]
