# Generated by Django 4.1 on 2022-09-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0045_remove_employee_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhar_card', models.FileField(blank=True, null=True, upload_to='employee_documents/adhar_card')),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='employee_documents/pan_card')),
                ('secondary_marksheet', models.FileField(blank=True, null=True, upload_to='employee_documents/secondary')),
                ('senior_secondary_marksheet', models.FileField(blank=True, null=True, upload_to='employee_documents/senior_secondary')),
                ('resume', models.FileField(blank=True, null=True, upload_to='employee_documents/resume')),
            ],
        ),
    ]
