# Generated by Django 4.1 on 2022-09-27 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0046_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
