# Generated by Django 4.1 on 2022-09-27 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ems', '0047_delete_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhar_card', models.FileField(blank=True, null=True, upload_to='employee_documents/adhar_card')),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='employee_documents/pan_card')),
                ('secondary_marksheet', models.FileField(blank=True, null=True, upload_to='employee_documents/secondary')),
                ('senior_secondary_marksheet', models.FileField(blank=True, null=True, upload_to='employee_documents/senior_secondary')),
                ('resume', models.FileField(blank=True, null=True, upload_to='employee_documents/resume')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ems.document'),
        ),
    ]
