# Generated by Django 4.1 on 2022-09-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0048_document_employee_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='mother_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
