# Generated by Django 4.1 on 2022-09-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0049_employee_mother_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='adhar_card',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pan_card',
        ),
        migrations.RemoveField(
            model_name='document',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='document',
            name='secondary_marksheet',
        ),
        migrations.RemoveField(
            model_name='document',
            name='senior_secondary_marksheet',
        ),
        migrations.AddField(
            model_name='document',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='employee_documents'),
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
