# Generated by Django 4.1 on 2022-09-28 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0050_remove_document_adhar_card_remove_document_pan_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='document',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
