# Generated by Django 4.1 on 2022-10-06 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0059_reimbursementtransport_delete_reimbursementcab'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReimbursementFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_employee', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('bill_number', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('remark', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems.employee')),
            ],
        ),
    ]
