# Generated by Django 4.1 on 2022-10-06 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0060_reimbursementfood'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReimbursementFoodEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reimbursement_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems.reimbursementfood')),
            ],
        ),
    ]
