# Generated by Django 4.1 on 2022-10-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0061_reimbursementfoodemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursementfood',
            name='amount',
            field=models.FloatField(),
        ),
    ]
