# Generated by Django 4.1 on 2022-10-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0062_alter_reimbursementfood_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocatedleave',
            name='month',
        ),
        migrations.AlterField(
            model_name='allocatedleave',
            name='earn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
