# Generated by Django 4.1 on 2022-10-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0063_remove_allocatedleave_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocatedleave',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allocatedleave',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
