# Generated by Django 4.1 on 2022-10-09 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0064_allocatedleave_end_date_allocatedleave_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='allocatedleave',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ems.employee'),
        ),
    ]
