# Generated by Django 4.1 on 2022-10-09 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0065_alter_employee_options_alter_allocatedleave_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReducedLeaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems.attendance')),
            ],
        ),
    ]
