# Generated by Django 4.1 on 2022-10-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0066_reducedleaves'),
    ]

    operations = [
        migrations.AddField(
            model_name='reducedleaves',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
    ]
