# Generated by Django 4.1 on 2022-10-09 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0068_reducedleaves_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReducedLeaves',
        ),
    ]
