# Generated by Django 4.1 on 2022-10-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0070_reducedleaves'),
    ]

    operations = [
        migrations.CreateModel(
            name='P_Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
