# Generated by Django 4.1 on 2022-10-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0072_employeepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocatedleave',
            name='total_leaves',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
