# Generated by Django 4.1 on 2022-10-26 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0073_allocatedleave_total_leaves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocatedleave',
            name='total_leaves',
        ),
    ]
